# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('thumbnail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightCode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=8)),
                ('date', models.DateTimeField()),
                ('roundTrip', models.NullBooleanField()),
                ('airline', models.CharField(max_length=20)),
            ],
        ),
    ]
